load("//devtools/taskrunner2:defs.bzl", "taskrunner2")

taskrunner2(
    name = "mothership",
    watch_targets = [
        "//tools/mothership/cmd/mship_api",
        "//tools/mothership/ui",
    ],
)
