load("//devtools/taskrunner2:defs.bzl", "taskrunner2")

taskrunner2(
    name = "mothership",
    targets = [
        "//devtools/devtemporal",
    ],
    watch_targets = [
        "//tools/mothership/cmd/mship_api",
        "//tools/mothership/ui",
    ],
)
