load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "storage",
    srcs = ["storage.go"],
    importpath = "go.resf.org/peridot/base/go/storage",
    visibility = ["//visibility:public"],
)
