load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "kv",
    srcs = ["kv.go"],
    importpath = "go.resf.org/peridot/base/go/kv",
    visibility = ["//visibility:public"],
)
